version: "3.8"
services:

  webapp:
    build: ./

  mongodb:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    # environment:
    # TODO: add this and use config
      # MONGO_INITDB_ROOT_USERNAME: root
      # MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - type: bind
        source: ./db-data
        target: /data/db
