version: "3.8"
services:

  webapp:
    ports:
      - "3000:3000"
    build: .
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      - DB_URI=mongodb://mongodb:27017/
      - DB_NAME=elixir
      - DB_USER=real-elixir-user
      - DB_PASS=not-so-secret-elixir-pass

  mongodb:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "real-elixir-user"
      MONGO_INITDB_ROOT_PASSWORD: "not-so-secret-elixir-pass"
    volumes:
      - type: bind
        source: ./db-data
        target: /data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 15s
      timeout: 30s
      retries: 5
      start_period: 15s
